AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple HTTP Web Application using Ubuntu 24.04"

Resources:
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access"
      SecurityGroupIngress:
        # Note: this is an YAML array of objects.
        # Each item in the array starts with a -
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup # This is defined in Resources.WebAppSecurityGroup
      ImageId: ami-0866a3c8686eaeeba # Replace with the Ubuntu 24.04 AMI ID in your region
      UserData:
        # For more information about the Fn::Sub function:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install -y apache2
          systemctl start apache2
          systemctl enable apache2
          echo "<h1>Hello, World! Welcome to My Web App on Ubuntu 24.04</h1>" > /var/www/html/index.html

Outputs:
  WebAppURL:
    Description: "URL for the web app"
    Value: !Sub "http://${WebAppInstance.PublicDnsName}"